name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install ast-grep
        run: npm install --global @ast-grep/cli
      - name: Format
        run: cargo fmt --check
      - name: Check
        run: cargo check --all-features
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test
      - name: ast-grep
        run: ast-grep scan
